apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: minibookkeeping
  annotations:
    github.com/project-slug: arivukaran/minibookkeeping
spec:
  type: other
  lifecycle: unknown
  owner: Prabhakaran
